project:
  type: website
  output-dir: docs
  
website:
  title: "Hafizur new website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - projects.qmd
    tools:
      - icon: twitter
        href: https://twitter.com/
      - icon: github
        href: https://github.com/mr1610/Hafizur_BIOL-806_new_website
  page-footer:
    right: "Built with [Quarto](https://quarto.org/)"
    left: "&copy; Copyright 2023, Md Hafizur Rahman"

format:
  html:
    theme: cerulean
    toc: true

editor: source

